<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageId>Play.Identity.Contracts</PackageId>
	  <PackageVersion>1.0.3</PackageVersion>
	  <Authors>patyfb04</Authors>
	  <RepositoryUrl>https://github.com/patyfb04/microservice</RepositoryUrl>
	  <PackageDescription>identity contracts</PackageDescription>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
