apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: play-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: identity.play.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: play-identity
                port:
                  number: 80

    - host: catalog.play.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: play-catalog
                port:
                  number: 80

    - host: inventory.play.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: play-inventory
                port:
                  number: 80

    - host: trading.play.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: play-trading
                port:
                  number: 80

    - host: play.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: play-frontend
                port:
                  number: 80
